### ISSUE TITLE
uenv: command not found

### ISSUE THREAD

**Issue by jgphpc** [eth-cscs/uenv-legacy#1]
uenv --version
> uenv version 0.1-dev

For users who do not add uenv in their ~/.bashrc, `uenv stop` will fail with:

```
source ~/.local/bin/activate-uenv
uenv start ./my.squashfs
uenv stop
bash: uenv: command not found
```

- `exit` works
- uenv is a function so `source ~/.local/bin/activate-uenv` + `uenv stop` works too

Worth adding a note in the doc ?

**Comment by bcumming** [comment]
Thanks @jgphpc.

When installing the tool, it explicitly prompts the user whether they want to update their `~/.bashrc`, and provides instructions on how to do it manually if they don't want it performed automatically.

**Comment by bcumming** [comment]
The front page of the docs also mentions this:

https://eth-cscs.github.io/uenv/

Is there something missing?
